quotatool test fixed

diff --git a/templates/quotatool.fact.j2 b/templates/quotatool.fact.j2
--- a/templates/quotatool.fact.j2
+++ b/templates/quotatool.fact.j2
@@ -4,16 +4,14 @@
 
 set -euo pipefail
 
+QUOTACHECK=$(quota -f {{ quota_dir | quote }} > /dev/null && echo "pass" || echo "fail")
 QUOTATOOL="{{ quota_quotatool }}"
 
-if quota -f {{ quota_dir | quote }}; then
+if [[ "${QUOTACHECK}" == "pass" ]]; then
   if [[ -f "${QUOTATOOL}" ]]; then
-  
     BLOCK_GRACE=$("${QUOTATOOL}" -v -n -u -b -t 86400 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $4 }')
     INODE_GRACE=$("${QUOTATOOL}" -v -n -u -i -t 86400 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $4 }')
-  
     jo state=present block_grace="${BLOCK_GRACE}" inode_grace="${INODE_GRACE}"
-  
   else
     jo state=absent
   fi
