Fix quotatool script so the correct values are saved

diff --git a/templates/quotatool.fact.j2 b/templates/quotatool.fact.j2
--- a/templates/quotatool.fact.j2
+++ b/templates/quotatool.fact.j2
@@ -4,15 +4,15 @@
 
 set -euo pipefail
 
-QUOTACHECK=$(quota -f {{ quota_dir | quote }} > /dev/null && echo "pass" || echo "fail")
-QUOTATOOL="{{ quota_quotatool }}"
+quotacheck=$(quota -f {{ quota_dir | quote }} > /dev/null && echo "pass" || echo "fail")
+quotatool="{{ quota_quotatool }}"
 
-if [[ "${QUOTACHECK}" == "pass" ]]; then
-  if [[ -f "${QUOTATOOL}" ]]; then
-    # quotatool uses -n for dry run so the value isn't changed and only te old quota value is saved
-    BLOCK_GRACE=$("${QUOTATOOL}" -v -n -u -b -t 10 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $3 }')
-    INODE_GRACE=$("${QUOTATOOL}" -v -n -u -i -t 10 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $3 }')
-    jo state=present block_grace="${BLOCK_GRACE}" inode_grace="${INODE_GRACE}"
+if [[ "${quotacheck}" == "pass" ]]; then
+  if [[ -f "${quotatool}" ]]; then
+    # quotatool uses -n for dry run so the value isn't changed and only the old quota value is saved
+    block_grace=$("${quotatool}" -v -n -u -b -t 10 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $4 }')
+    inode_grace=$("${quotatool}" -v -n -u -i -t 10 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $4 }')
+    jo state=present block_grace="${block_grace}" inode_grace="${inode_grace}"
   else
     jo state=absent
   fi
