Various updates

diff --git a/templates/quotatool.fact.j2 b/templates/quotatool.fact.j2
--- a/templates/quotatool.fact.j2
+++ b/templates/quotatool.fact.j2
@@ -4,14 +4,24 @@
 
 set -euo pipefail
 
-quotacheck=$(quota -f {{ quota_dir | quote }} > /dev/null && echo "pass" || echo "fail")
-quotatool="{{ quota_quotatool }}"
+jo=$(type -P jo || echo "absent")
+quota=$(type -P quota || echo "absent")
+quotatool=$(type -P quotatool || echo "absent")
 
-if [[ "${quotacheck}" == "pass" && -f "${quotatool}" ]]; then
-  # quotatool uses -n for dry run so the value isn't changed and only the old quota value is saved
-  block_grace=$("${quotatool}" -v -n -u -b -t 10 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $4 }')
-  inode_grace=$("${quotatool}" -v -n -u -i -t 10 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $4 }')
-  jo state=present block_grace="${block_grace}" inode_grace="${inode_grace}"
+if [[ "${quota}" != "absent" ]]; then
+  quotacheck=$("${quota}" -f {{ quota_dir | quote }} > /dev/null && echo "pass" || echo "fail")
+  if [[ "${quotatool}" != "absent" && "${quotacheck}" == "pass" ]]; then
+    # quotatool uses -n for dry run so the value isn't changed and only the old quota value is saved
+    block_grace=$("${quotatool}" -v -n -u -b -t 10 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $4 }')
+    inode_grace=$("${quotatool}" -v -n -u -i -t 10 {{ quota_dir | quote }} 2>&1 | tail -n1 | awk '{ print $4 }')
+    "${jo}" state=present block_grace="${block_grace}" inode_grace="${inode_grace}"
+  else
+    "${jo}" state=absent
+  fi
 else
-  jo state=absent
+  if [[ "${jo}" != "absent" ]]; then
+    "${jo}" state=absent
+  else
+    echo '{"state":"absent"}'
+  fi
 fi
diff --git a/templates/repquota.fact.j2 b/templates/repquota.fact.j2
--- a/templates/repquota.fact.j2
+++ b/templates/repquota.fact.j2
@@ -4,11 +4,26 @@
 
 set -euo pipefail
 
-jc="{{ quota_jc }}"
-repquota="{{ quota_repquota }}"
+jc=(type -P jc || echo "absent")
+jo=$(type -P jo || echo "absent")
+quota=$(type -P quota || echo "absent")
+repquota=(type -P repquota || echo "absent")
 
-if [[ -f "${jc}" && -f "${repquota}" && -f "{{ quota_dir }}/aquota.user" ]]; then
-  ${repquota} "{{ quota_dir }}" -O csv | ${jc} -m --csv 
+if [[ "${quota}" != "absent" ]]; then
+  quotacheck=$("${quota}" -f "{{ quota_dir }}" > /dev/null && echo "pass" || echo "fail")
+  if [[ "${jc}" != "absent" && "${repquota}" != "absent" && "${quotacheck}" == "pass" ]]; then
+    "${repquota}" "{{ quota_dir }}" -O csv | "${jc}" -m --csv 
+  else
+    if [[ "${jo}" != "absent" ]]; then
+      "${jo}" state=absent
+    else
+      echo '{"state":"absent"}'
+    fi
+  fi
 else
-  jo state=absent
+  if [[ "${jo}" != "absent" ]]; then
+    "${jo}" state=absent
+  else
+    echo '{"state":"absent"}'
+  fi
 fi
